


# IW ---SN
# 3----254
import string
import time

f_alist=[]
alphabet =string.ascii_uppercase
# zgg_inn  1
str_1 = '.add_yaxis(\n"{0}",\ny_axis=f_y_data_{1},\nlinestyle_opts=opts.LineStyleOpts(width=1),\nlabel_opts=opts.LabelOpts(is_label_show=True,is_legend_show=False), symbol_size=1\n)'

sp_nas_zgg = 'ZZG_index,A,AAL,AAPL,ABBV,ABC,ABMD,ABT,ACN,ADBE,ADI,ADM,ADP,ADS,ADSK,AEE,AEP,AES,AFL,AGN,AIG,AIV,AIZ,AJG,AKAM,ALB,ALGN,ALK,ALL_,ALLE,ALXN,AMAT,AMD,AME,AMGN,AMP,AMT,AMZN,ANSS,AON,AOS,APA,APD,APH,APTV,ARE,ASML,ATO,ATVI,AVB,AVGO,AVY,AWK,AXP,AZO,BA,BAC,BAX,BBY,BDX,BEN,BF_B,BIDU,BIIB,BK,BLK,BLL,BMRN,BMY,BR,BRK_B,BSX,BWA,BXP,C,CAG,CAH,CAT,CB,CBOE,CCI,CCL,CDNS,CDW,CE,CERN,CF,CHD,CHKP,CHRW,CHTR,CI,CINF,CL,CLX,CMA,CMCSA,CME,CMG,CMI,CMS,CNC,CNP,COF,COG,COO,COP,COST,COTY,CPB,CPRI,CPRT,CRM,CSCO,CSGP,CSX,CTAS,CTL,CTSH,CTXS,CVS,CVX,CXO,D,DAL,DE,DFS,DG,DGX,DHI,DHR,DIS,DISCA,DISCK,DISH,DLR,DLTR,DOV,DRE,DRI,DTE,DUK,DVA,DVN,DXC,EA,EBAY,ECL,ED,EFX,EIX,EL,EMN,EMR,EOG,EQIX,EQR,ESS,ETFC,ETN,ETR,EW,EXC,EXPD,F,FAST,FB,FCX,FDX,FE,FFIV,FIS,FISV,FITB,FLIR,FLS,FLT,FMC,FOX,FOXA,FRC,FRT,FTI,FTNT,FTV,GD,GE,GILD,GIS,GLW,GM,GOOG,GOOGL,GPC,GPN,GPS,GRMN,GS,GWW,HAL,HAS,HBAN,HBI,HCA,HD,HES,HFC,HIG,HLT,HOG,HOLX,HON,HP,HPE,HPQ,HRB,HRL,HSIC,HST,HSY,HUM,IBM,ICE,IDXX,IEX,IFF,INCY,INFO,INTC,INTU,IP,IPG,IPGP,IR,IRM,ISRG,IT,ITW,IVZ,JBHT,JCI,JD,JKHY,JNJ,JNPR,JPM,JWN,K,KEY_,KHC,KIM,KLAC,KMB,KMI,KMX,KO,KR,KSS,KSU,L,LBTYA,LBTYK,LEG,LEN,LH,LKQ,LLY,LMT,LNC,LNT,LOW,LRCX,LUV,LVS,LYB,M,MA,MAA,MAR,MAS,MCD,MCHP,MCK,MCO,MDLZ,MDT,MET,MGM,MHK,MKC,MLM,MMC,MMM,MNST,MO,MOS,MPC,MRK,MRO,MS,MSFT,MSI,MTB,MTD,MU,MXIM,MYL,NBL,NCLH,NDAQ,NEE,NEM,NFLX,NI,NKE,NLSN,NOC,NOV,NOW,NRG,NSC,NTAP,NTES,NTRS,NUE,NVDA,NWL,NWS,NWSA,NXPI,O,OKE,OMC,ORCL,ORLY,OXY,PAYX,PBCT,PCAR,PEG,PEP,PFE,PFG,PG,PGR,PH,PHM,PKG,PKI,PLD,PM,PNC,PNR,PNW,PPG,PPL,PRGO,PRU,PSA,PSX,PVH,PWR,PXD,PYPL,QCOM,RCL,RE,REG,REGN,RF,RHI,RJF,RL,RMD,ROK,ROP,ROST,RSG,RTN,SBAC,SBUX,SCHW,SEE,SHW,SIVB,SJM,SLB,SLG,SNA,SNPS,SO,SPG,SPGI,SRE,STE,STT,STX,STZ,SWK,SWKS,SYF,SYK,SYY,T,TAP,TEL,TFX,TGT,TIF,TJX,TMO,TROW,TRV,TSCO,TSLA,TSN,TWTR,TXN,TXT,UA,UAL,UDR,ULTA,UNH,UNM,UNP,UPS,URI,USB,UTX,V,VAR,VFC,VLO,VMC,VNO,VRSN,VRTX,VTR,VZ,WAB,WAT,WBA,WDAY,WDC,WEC,WFC,WHR,WLTW,WM,WMB,WMT,WRB,WRK,WU,WY,WYNN,XEC,XEL,XLNX,XOM,XRAY,XRX,XYL,YUM,ZBRA,ZION'


f_snz = sp_nas_zgg.split(",")

for c,n in zip(range(1,468),f_snz) :

    f_code=str_1.format(n,c)




    try:
        with open('n.txt', 'a') as file_handle:
            # .txt可以不自己新建,代码会自动新建
            file_handle.write(f_code + "")  # 写入
            file_handle.write('\n')  # 有时放在循环里面需要自动转行，不然会覆盖上一条数据
            print("{0} 整理完毕".format("N.txt"))
    except:
        pass


